(function($,undefined){$.each("touchstart touchmove touchend orientationchange tap taphold swipe swipeleft swiperight scrollstart scrollstop".split(" "),function(i,name){$.fn[name]=function(fn){return fn?this.bind(name,fn):this.trigger(name);};$.attrFn[name]=true;});var supportTouch=('ontouchstart'in window),scrollEvent="touchmove scroll",touchStartEvent=supportTouch?"touchstart":"mousedown",touchStopEvent=supportTouch?"touchend":"mouseup",touchMoveEvent=supportTouch?"touchmove":"mousemove";$.event.special.scrollstart={enabled:true,setup:function(){var thisObject=this,$this=$(thisObject),scrolling,timer;function trigger(event,state){scrolling=state;var originalType=event.type;event.type=scrolling?"scrollstart":"scrollstop";$.event.handle.call(thisObject,event);event.type=originalType;}
$this.bind(scrollEvent,function(event){if(!$.event.special.scrollstart.enabled){return;}
if(!scrolling){trigger(event,true);}
clearTimeout(timer);timer=setTimeout(function(){trigger(event,false);},50);});}};$.event.special.tap={setup:function(){var thisObject=this,$this=$(thisObject);$this.bind(touchStartEvent,function(event){if(event.which&&event.which!==1||$this.data("prevEvent")&&$this.data("prevEvent")!==event.type){return false;}
$this.data("prevEvent",event.type);setTimeout(function(){$this.removeData("prevEvent");},800);var moved=false,touching=true,origTarget=event.target,origEvent=event.originalEvent,origPos=event.type=="touchstart"?[origEvent.touches[0].pageX,origEvent.touches[0].pageY]:[event.pageX,event.pageY],originalType,timer;function moveHandler(event){if(event.type=="scroll"){moved=true;return;}
var newPageXY=event.type=="touchmove"?event.originalEvent.touches[0]:event;if((Math.abs(origPos[0]- newPageXY.pageX)>10)||(Math.abs(origPos[1]- newPageXY.pageY)>10)){moved=true;}}
timer=setTimeout(function(){if(touching&&!moved){originalType=event.type;event.type="taphold";$.event.handle.call(thisObject,event);event.type=originalType;}},750);$(window).one("scroll",moveHandler);$this.bind(touchMoveEvent,moveHandler).one(touchStopEvent,function(event){$this.unbind(touchMoveEvent,moveHandler);$(window).unbind("scroll",moveHandler);clearTimeout(timer);touching=false;if(!moved&&(origTarget==event.target)){originalType=event.type;event.type="tap";$.event.handle.call(thisObject,event);event.type=originalType;}});});}};$.event.special.swipe={setup:function(){var thisObject=this,$this=$(thisObject);$this.bind(touchStartEvent,function(event){var data=event.originalEvent.touches?event.originalEvent.touches[0]:event,start={time:(new Date).getTime(),coords:[data.pageX,data.pageY],origin:$(event.target)},stop;function moveHandler(event){if(!start){return;}
var data=event.originalEvent.touches?event.originalEvent.touches[0]:event;stop={time:(new Date).getTime(),coords:[data.pageX,data.pageY]};if(Math.abs(start.coords[0]- stop.coords[0])>10){event.preventDefault();}}
$this.bind(touchMoveEvent,moveHandler).one(touchStopEvent,function(event){$this.unbind(touchMoveEvent,moveHandler);if(start&&stop){if(stop.time- start.time<1000&&Math.abs(start.coords[0]- stop.coords[0])>30&&Math.abs(start.coords[1]- stop.coords[1])<75){start.origin.trigger("swipe").trigger(start.coords[0]>stop.coords[0]?"swipeleft":"swiperight");}}
start=stop=undefined;});});}};(function($){var win=$(window),special_event,get_orientation,last_orientation;$.event.special.orientationchange=special_event={setup:function(){if($.support.orientation){return false;}
last_orientation=get_orientation();win.bind("resize",handler);},teardown:function(){if($.support.orientation){return false;}
win.unbind("resize",handler);},add:function(handleObj){var old_handler=handleObj.handler;handleObj.handler=function(event){event.orientation=get_orientation();return old_handler.apply(this,arguments);};}};function handler(){var orientation=get_orientation();if(orientation!==last_orientation){last_orientation=orientation;win.trigger("orientationchange");}};special_event.orientation=get_orientation=function(){var elem=document.documentElement;return elem&&elem.clientWidth/elem.clientHeight<1.1?"portrait":"landscape";};})(jQuery);$.each({scrollstop:"scrollstart",taphold:"tap",swipeleft:"swipe",swiperight:"swipe"},function(event,sourceEvent){$.event.special[event]={setup:function(){$(this).bind(sourceEvent,$.noop);}};});})(jQuery);